---
abstract: 'Dist::Zilla plugin for Test::Kwalitee::Extra'
author:
  - 'Yasutaka ATARASHI <yakex@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-Kwalitee-Extra
requires:
  Dist::Zilla: 0
  Moose: 0
  Test::Kwalitee::Extra: 0
  Test::More: 0
  perl: 5.006
version: v0.0.1
